source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SweetToasts_Example', :exclusive => true do
  pod 'SweetToasts', :path => '../'
end

target 'SweetToasts_Tests', :exclusive => true do
  pod 'SweetToasts', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
